# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clerk < Formula
  desc "The Claude Code Clerk — auto-summarize your sessions"
  homepage "https://github.com/vulcanshen/clerk"
  version "3.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/clerk/releases/download/v3.6.0/clerk_3.6.0_darwin_amd64.tar.gz"
      sha256 "4254be75335bdc67117f714d6414adf3d5426e03d75b4ebf5d47f7c682661134"

      define_method(:install) do
        bin.install "clerk"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/clerk/releases/download/v3.6.0/clerk_3.6.0_darwin_arm64.tar.gz"
      sha256 "a7be44ef4287ca92fbf9c7953e1365a196ac27d966a25086b140267b9a169212"

      define_method(:install) do
        bin.install "clerk"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/clerk/releases/download/v3.6.0/clerk_3.6.0_linux_amd64.tar.gz"
      sha256 "59c1f521da39e9b0060ab8878842a9673527f1f73a0daf314d55ed847a845d0f"
      define_method(:install) do
        bin.install "clerk"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/clerk/releases/download/v3.6.0/clerk_3.6.0_linux_arm64.tar.gz"
      sha256 "b3b25172d24bc6ea31f349748d5ec8d668bdb9f020b528f4a1c6b762e3352a0b"
      define_method(:install) do
        bin.install "clerk"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end
end
