# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clerk < Formula
  desc "The Claude Code Clerk — auto-summarize your sessions"
  homepage "https://github.com/vulcanshen/clerk"
  version "5.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/clerk/releases/download/v5.1.1/clerk_5.1.1_darwin_amd64.tar.gz"
      sha256 "773e0a557b97f19cecd056db50114e78954ce07e9cd4563e5bb11cc9b33e277e"

      define_method(:install) do
        bin.install "clerk"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/clerk/releases/download/v5.1.1/clerk_5.1.1_darwin_arm64.tar.gz"
      sha256 "b0984f29da5a20d56389517c5a3b5d7e88c5e55f7088dcc6ae4045d4beaa1905"

      define_method(:install) do
        bin.install "clerk"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/clerk/releases/download/v5.1.1/clerk_5.1.1_linux_amd64.tar.gz"
      sha256 "6a20f8d452477b2a48361d63f886f5a57b52f6b2b0766231b91c9a99c0317deb"
      define_method(:install) do
        bin.install "clerk"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/clerk/releases/download/v5.1.1/clerk_5.1.1_linux_arm64.tar.gz"
      sha256 "da08e1a8fde8e88baf9a9725b0fccee9d9ecc8f920dd990dfa3af8c5e5ee0001"
      define_method(:install) do
        bin.install "clerk"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end
end
