# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filu < Formula
  desc "ZLC terminal file manager (kbu u-family) — content search, split preview, carry-bucket"
  homepage "https://github.com/vulcanshen/filu"
  version "0.2.0"

  depends_on "fd"
  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/filu/releases/download/v0.2.0/filu_0.2.0_darwin_amd64.tar.gz"
      sha256 "56f37c21dabc5fd383f735a476a750d4ddf0e2f6cb8fd262841f5ad45279ba4c"

      define_method(:install) do
        bin.install "filu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/filu/releases/download/v0.2.0/filu_0.2.0_darwin_arm64.tar.gz"
      sha256 "445e07b7d8935d7e9263ff97609a33ff6cb4c7f2fa99ae1d65ca226c5656448d"

      define_method(:install) do
        bin.install "filu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/filu/releases/download/v0.2.0/filu_0.2.0_linux_amd64.tar.gz"
      sha256 "24b9543b5d49fd97bd7679be18ebe97fd66d202462ed372d2d31cb1846f16fd0"
      define_method(:install) do
        bin.install "filu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/filu/releases/download/v0.2.0/filu_0.2.0_linux_arm64.tar.gz"
      sha256 "b1c5d77f5d0babdfb060bf8bd08fd0f4eef6eb28de73fe8945b99c26d6f61413"
      define_method(:install) do
        bin.install "filu"
      end
    end
  end
end
