# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filu < Formula
  desc "ZLC terminal file manager (kbu u-family) — content search, split preview, carry-bucket"
  homepage "https://github.com/vulcanshen/filu"
  version "0.2.8"

  depends_on "fd"
  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/filu/releases/download/v0.2.8/filu_0.2.8_darwin_amd64.tar.gz"
      sha256 "8fadc302516169e0f8e2bacc36e5165bb1d42d6e0d36ceab25a509d35c1fcebc"

      define_method(:install) do
        bin.install "filu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/filu/releases/download/v0.2.8/filu_0.2.8_darwin_arm64.tar.gz"
      sha256 "9094a47f6647058f64b4a73a57eb3f873e391b41f2cc273fc51d713e2953938b"

      define_method(:install) do
        bin.install "filu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/filu/releases/download/v0.2.8/filu_0.2.8_linux_amd64.tar.gz"
      sha256 "c84ec9c57e8ea71fda2e5ef522512213403f2f6181f9f64bcaa31d26d18b4f15"
      define_method(:install) do
        bin.install "filu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/filu/releases/download/v0.2.8/filu_0.2.8_linux_arm64.tar.gz"
      sha256 "5728fe5fbf9ab0f88f61d8d3cbadd8e8c7225fdcf51de5e6803c81522357e79a"
      define_method(:install) do
        bin.install "filu"
      end
    end
  end
end
