# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostfile < Formula
  desc "Cross-platform hosts file manager CLI"
  homepage "https://github.com/vulcanshen/hostfile"
  version "1.5.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/hostfile/releases/download/v1.5.3/hostfile_1.5.3_darwin_amd64.tar.gz"
      sha256 "087fcb7c398e53092eeee559d8b162e19fe05cefbb84c17d78ad7aa82cbbd6f1"

      define_method(:install) do
        bin.install "hostfile"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/hostfile/releases/download/v1.5.3/hostfile_1.5.3_darwin_arm64.tar.gz"
      sha256 "7d8efd2c7e73d972dc24fec6e1b32f19919ad96f1057813a56659eb8f742b3b1"

      define_method(:install) do
        bin.install "hostfile"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/hostfile/releases/download/v1.5.3/hostfile_1.5.3_linux_amd64.tar.gz"
      sha256 "2ef9e92282c1b47b1ee3d428689ce53d82206c013d8562b46441a0f0562c5db8"
      define_method(:install) do
        bin.install "hostfile"
        man1.install Dir["docs/man/*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/hostfile/releases/download/v1.5.3/hostfile_1.5.3_linux_arm64.tar.gz"
      sha256 "e0e959b855156a110c502c8ca46b1d502d0cdaa6e2734ad857c4f4cbe746aa58"
      define_method(:install) do
        bin.install "hostfile"
        man1.install Dir["docs/man/*.1"]
      end
    end
  end
end
