# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hostfile < Formula
  desc "Cross-platform hosts file manager CLI"
  homepage "https://github.com/vulcanshen/hostfile"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/hostfile/releases/download/v1.1.2/hostfile_1.1.2_darwin_amd64.tar.gz"
      sha256 "8b3493683189bac8fe9e0c59aefa9e98c2e94e89513d53fb55534c67197041e6"

      define_method(:install) do
        bin.install "hostfile"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/hostfile/releases/download/v1.1.2/hostfile_1.1.2_darwin_arm64.tar.gz"
      sha256 "6e511cb9c0c62617dcef51ff800c01ceec7b49011c5418015d391780c8691fae"

      define_method(:install) do
        bin.install "hostfile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/hostfile/releases/download/v1.1.2/hostfile_1.1.2_linux_amd64.tar.gz"
      sha256 "bbae34e4ef96422fa954980130d393e002dc43a9a1d78688e7a2e8fe3afbdf2a"
      define_method(:install) do
        bin.install "hostfile"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/hostfile/releases/download/v1.1.2/hostfile_1.1.2_linux_arm64.tar.gz"
      sha256 "573281e97a34daa0fad27dbbd3b147f4c6b1b38e192f88facb5de4cddce2cf36"
      define_method(:install) do
        bin.install "hostfile"
      end
    end
  end
end
