# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbu < Formula
  desc "Kubernetes TUI management tool inspired by Lens IDE"
  homepage "https://github.com/vulcanshen/kbu"
  version "2.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/kbu/releases/download/v2.0.2/kbu_2.0.2_darwin_amd64.tar.gz"
      sha256 "530702a6b1d562ec3c3843ddb5e207adf370b841cd95d4a2bd9c694c69f293f0"

      define_method(:install) do
        bin.install "kbu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/kbu/releases/download/v2.0.2/kbu_2.0.2_darwin_arm64.tar.gz"
      sha256 "806245e2ecb4fc1dc0fd3a980486753fcbdaa5833cf54434f8524f2c1060ba6e"

      define_method(:install) do
        bin.install "kbu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/kbu/releases/download/v2.0.2/kbu_2.0.2_linux_amd64.tar.gz"
      sha256 "4d2b33a40631591881eb41a97e426b89417ed0b5e7a58e5c86f38e495a70a01e"
      define_method(:install) do
        bin.install "kbu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/kbu/releases/download/v2.0.2/kbu_2.0.2_linux_arm64.tar.gz"
      sha256 "93cbde0adc835798cd263d57243c5bad472a54e0f34f6be5271df10032115a93"
      define_method(:install) do
        bin.install "kbu"
      end
    end
  end
end
