# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbu < Formula
  desc "Kubernetes TUI management tool inspired by Lens IDE"
  homepage "https://github.com/vulcanshen/kbu"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/kbu/releases/download/v2.1.0/kbu_2.1.0_darwin_amd64.tar.gz"
      sha256 "ff41d7baa7217e11f109e058a97a91d93e968a3c504db61fe3df434e16c587ed"

      define_method(:install) do
        bin.install "kbu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/kbu/releases/download/v2.1.0/kbu_2.1.0_darwin_arm64.tar.gz"
      sha256 "7c539759e4b578c5ccbf5cec74d266d4d9c010b8518ad24fd0aae998e1766e61"

      define_method(:install) do
        bin.install "kbu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/kbu/releases/download/v2.1.0/kbu_2.1.0_linux_amd64.tar.gz"
      sha256 "a04507c76afbdb5497c32c8e80a3cc355903328a9552364f004c4773a5959d43"
      define_method(:install) do
        bin.install "kbu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/kbu/releases/download/v2.1.0/kbu_2.1.0_linux_arm64.tar.gz"
      sha256 "36e064c4cec34b1c258b3a64a0ac80cd8c3af576dbeeb17ecdb768e013ad8e1c"
      define_method(:install) do
        bin.install "kbu"
      end
    end
  end
end
