# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locku < Formula
  desc "screensaver with a PIN for the terminal (u-family) — tmux lock-command, screen LOCKPRG, or any tty: an LED-board clock, a dino run, or a program of your own; any key asks for the PIN"
  homepage "https://github.com/vulcanshen/locku"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.3/locku_0.2.3_darwin_amd64.tar.gz"
      sha256 "c74ea6d0f6c4e1bf5fbcf0c78fab4ff4f1da19f9a79eda39f681317845c00544"

      define_method(:install) do
        bin.install "locku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.3/locku_0.2.3_darwin_arm64.tar.gz"
      sha256 "e46cf0e8f98b04c0dfd485f98b78f1e4a6328ccf688543a3ffa708f6ed1016ca"

      define_method(:install) do
        bin.install "locku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.3/locku_0.2.3_linux_amd64.tar.gz"
      sha256 "bf8a5a8a697ed3369b8be97bfc09bbfdec78256af0f7593e4ef4cfbf7ffda53a"
      define_method(:install) do
        bin.install "locku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.3/locku_0.2.3_linux_arm64.tar.gz"
      sha256 "3aa8b87f220eb97994c2515898e128b71d37e1a5fc91e9a52fc0d14f9649a6c7"
      define_method(:install) do
        bin.install "locku"
      end
    end
  end

  def caveats
    <<~EOS
      `locku` is the settings screen: the PIN, the savers and their
      profiles, and Integration › tmux / screen — turn `activate` on
      there and locku writes its block into ~/.tmux.conf (applied to a
      running server too) or ~/.screenrc plus your shell rc (LOCKPRG).
      Without a PIN the lock is a screensaver that any key ends. A PIN
      forgotten: `locku pin reset`, from any shell of your own.

      A Nerd Font terminal profile is required: the board's pixels are
      Nerd Font glyphs. macOS and Linux (WSL too); Windows is not
      supported.
    EOS
  end

  test do
    system "#{bin}/locku", "version"
  end
end
