# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locku < Formula
  desc "screensaver with a PIN for the terminal (u-family) — tmux lock-command, screen LOCKPRG, or any tty: an LED-board clock, a dino run, or a program of your own; any key asks for the PIN"
  homepage "https://github.com/vulcanshen/locku"
  version "0.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.6/locku_0.2.6_darwin_amd64.tar.gz"
      sha256 "89d2ee1342b324de276ca40dd8c9a8dc8a3e215571adc560a8591ccd0e396e7a"

      define_method(:install) do
        bin.install "locku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.6/locku_0.2.6_darwin_arm64.tar.gz"
      sha256 "452ca2bb9fd10f4e304a9afec21b8f2ffa7d66b0d69a1193e5d2696ba7740ffe"

      define_method(:install) do
        bin.install "locku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.6/locku_0.2.6_linux_amd64.tar.gz"
      sha256 "8754931125b997fbfffbdd1c377f9566982d1d827123d2c6962cb4054e3c75e7"
      define_method(:install) do
        bin.install "locku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.6/locku_0.2.6_linux_arm64.tar.gz"
      sha256 "b9ed35da70661a84661df7bb8b1b44cf9acfc34be7f0c3b7d7857069b1e166fe"
      define_method(:install) do
        bin.install "locku"
      end
    end
  end

  def caveats
    <<~EOS
      `locku` is the settings screen: the PIN, the savers and their
      profiles, and Integration › tmux / screen — turn `activate` on
      there and locku writes its block into ~/.tmux.conf (applied to a
      running server too) or ~/.screenrc plus your shell rc (LOCKPRG).
      Without a PIN the lock is a screensaver that any key ends. A PIN
      forgotten: `locku pin reset`, from any shell of your own.

      A Nerd Font terminal profile is required: the board's pixels are
      Nerd Font glyphs. macOS and Linux (WSL too); Windows is not
      supported.
    EOS
  end

  test do
    system "#{bin}/locku", "version"
  end
end
