# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Locku < Formula
  desc "screensaver with a PIN for the terminal (u-family) — tmux lock-command, screen LOCKPRG, or any tty: an LED-board clock, a dino run, or a program of your own; any key asks for the PIN"
  homepage "https://github.com/vulcanshen/locku"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.4/locku_0.2.4_darwin_amd64.tar.gz"
      sha256 "1c8e1248a57cb0870139eaad59f91b06e7baf378dd0ded6a347665beffde2a5e"

      define_method(:install) do
        bin.install "locku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.4/locku_0.2.4_darwin_arm64.tar.gz"
      sha256 "99c9c40773e7a76c8d50ff40ab57e129da1dfccba53de1f8fc42858a02dc7b3d"

      define_method(:install) do
        bin.install "locku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.4/locku_0.2.4_linux_amd64.tar.gz"
      sha256 "0cdca35d31fb3d333033f96943a5d382e52084fb4283f2a324866a5dfa46f2e3"
      define_method(:install) do
        bin.install "locku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/locku/releases/download/v0.2.4/locku_0.2.4_linux_arm64.tar.gz"
      sha256 "eb36483e069fe6c8dab9404bbaaa131c8e706c04451be3be9479bfcfe940a772"
      define_method(:install) do
        bin.install "locku"
      end
    end
  end

  def caveats
    <<~EOS
      `locku` is the settings screen: the PIN, the savers and their
      profiles, and Integration › tmux / screen — turn `activate` on
      there and locku writes its block into ~/.tmux.conf (applied to a
      running server too) or ~/.screenrc plus your shell rc (LOCKPRG).
      Without a PIN the lock is a screensaver that any key ends. A PIN
      forgotten: `locku pin reset`, from any shell of your own.

      A Nerd Font terminal profile is required: the board's pixels are
      Nerd Font glyphs. macOS and Linux (WSL too); Windows is not
      supported.
    EOS
  end

  test do
    system "#{bin}/locku", "version"
  end
end
