# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshu < Formula
  desc "ssh/sftp terminal front end (u-family) — host book, reusable credentials, two-sided transfers, a grid of live terminals"
  homepage "https://github.com/vulcanshen/sshu"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/sshu/releases/download/v0.1.1/sshu_0.1.1_darwin_amd64.tar.gz"
      sha256 "a4ee7335a749f33bab4713c1952a826f0e18a027dbc1984405fa3d90f60cda22"

      define_method(:install) do
        bin.install "sshu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/sshu/releases/download/v0.1.1/sshu_0.1.1_darwin_arm64.tar.gz"
      sha256 "57fa36b12acb3b6076bcd893b352c91547f3f22818b81cdfa1dadfb231ace965"

      define_method(:install) do
        bin.install "sshu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/sshu/releases/download/v0.1.1/sshu_0.1.1_linux_amd64.tar.gz"
      sha256 "c526fdac17662d313e00688b4df062a69fb3409c72c2eb788b790b7dc72532ee"
      define_method(:install) do
        bin.install "sshu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/sshu/releases/download/v0.1.1/sshu_0.1.1_linux_arm64.tar.gz"
      sha256 "326858fc63dad584827680cfc30431f32d5d4a61e828fdcfcb0254e103722660"
      define_method(:install) do
        bin.install "sshu"
      end
    end
  end
end
