# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshu < Formula
  desc "ssh/sftp terminal front end (u-family) — host book, reusable credentials, two-sided transfers, a grid of live terminals"
  homepage "https://github.com/vulcanshen/sshu"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/sshu/releases/download/v1.1.0/sshu_1.1.0_darwin_amd64.tar.gz"
      sha256 "0352a1d92fb076d78fd26b82200b44a4c38cc50f536e39c7ab153f905a8afe75"

      define_method(:install) do
        bin.install "sshu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/sshu/releases/download/v1.1.0/sshu_1.1.0_darwin_arm64.tar.gz"
      sha256 "7d4fd14474561e773e6e81ef1ecb62cc096e00be9e6cf237678d6dbb673fd57c"

      define_method(:install) do
        bin.install "sshu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/sshu/releases/download/v1.1.0/sshu_1.1.0_linux_amd64.tar.gz"
      sha256 "192356f495c736292ba529b8e0b8c0c366c54426c5ddcb7b2eb39a5e5a3271d2"
      define_method(:install) do
        bin.install "sshu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/sshu/releases/download/v1.1.0/sshu_1.1.0_linux_arm64.tar.gz"
      sha256 "713d71a0ca6a6395c90fe98f5cf2c6fd32120c2c2614d7ed2f2871c61e80bd41"
      define_method(:install) do
        bin.install "sshu"
      end
    end
  end
end
