# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshu < Formula
  desc "ssh/sftp terminal front end (u-family) — host book, reusable credentials, two-sided transfers, a grid of live terminals"
  homepage "https://github.com/vulcanshen/sshu"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/sshu/releases/download/v0.1.0/sshu_0.1.0_darwin_amd64.tar.gz"
      sha256 "ba4db2a5b1e0e0521739e2481e867af3f95a9aefc5ee266088258c857724c9c8"

      define_method(:install) do
        bin.install "sshu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/sshu/releases/download/v0.1.0/sshu_0.1.0_darwin_arm64.tar.gz"
      sha256 "435ae935c44da5f470ffdf6a60cfe7bb59941229c7adc48ae8e6f831528ef7c2"

      define_method(:install) do
        bin.install "sshu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/sshu/releases/download/v0.1.0/sshu_0.1.0_linux_amd64.tar.gz"
      sha256 "a85bd88442ba9ea33e706fed0cb97daa5fb8629ba36328e98b531678f33dcab0"
      define_method(:install) do
        bin.install "sshu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/sshu/releases/download/v0.1.0/sshu_0.1.0_linux_arm64.tar.gz"
      sha256 "b21f1e9ab382b98037b5c1205bf01a17abd25b35b417ecefca7d820d11a64b9b"
      define_method(:install) do
        bin.install "sshu"
      end
    end
  end
end
