# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webu < Formula
  desc "terminal browser (u-family) — headless Chromium's accessibility tree, drawn as a TUI: tabs, bookmarks, history, downloads, DevTools"
  homepage "https://github.com/vulcanshen/webu"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/webu/releases/download/v0.4.0/webu_0.4.0_darwin_amd64.tar.gz"
      sha256 "03eec1d5482752e7aebf53cda2519a5f955c5254967abcd83f20c1ed3c0477f4"

      define_method(:install) do
        bin.install "webu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/webu/releases/download/v0.4.0/webu_0.4.0_darwin_arm64.tar.gz"
      sha256 "e5447105bc40d8f4c608829af9e2d6e84f45e2c39cb283a41726bc8d4dc84d1b"

      define_method(:install) do
        bin.install "webu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/webu/releases/download/v0.4.0/webu_0.4.0_linux_amd64.tar.gz"
      sha256 "4210c08c3987611bb685cfb4f27e9a667331edd51d58ff30a31a97562c84cc85"
      define_method(:install) do
        bin.install "webu"
      end
    end
  end

  def caveats
    <<~EOS
      webu runs its own Chromium (a pinned revision), fetched once on the
      first launch — about 175–250 MB into the cache directory (macOS:
      ~/Library/Caches/webu, Linux: ~/.cache/webu). After an upgrade that
      pins a new revision, `webu browser update` fetches it.

      Settings and bookmarks live in ~/.config/webu; history, session,
      downloads and the browser profile in ~/.webu/datas.

      A Nerd Font terminal profile is required: links, media, panels and
      the header are drawn with Nerd Font glyphs.
    EOS
  end

  test do
    system "#{bin}/webu", "version"
  end
end
