# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webu < Formula
  desc "terminal browser (u-family) — headless Chromium's accessibility tree, drawn as a TUI: tabs, bookmarks, history, downloads, DevTools"
  homepage "https://github.com/vulcanshen/webu"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/webu/releases/download/v0.1.0/webu_0.1.0_darwin_amd64.tar.gz"
      sha256 "5044658d34450818f7ee9d3c7167bcecde7774d13a22dbe0de4d83c48ba0d9d5"

      define_method(:install) do
        bin.install "webu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/webu/releases/download/v0.1.0/webu_0.1.0_darwin_arm64.tar.gz"
      sha256 "d76f9d095367640361ed2f8bc04ddf992fdb4070eeecb50e876922f1cb0702d7"

      define_method(:install) do
        bin.install "webu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/webu/releases/download/v0.1.0/webu_0.1.0_linux_amd64.tar.gz"
      sha256 "e9b5ba06785bbec632edd9afa2220e3cf460ecab64982639723795cf5a7b9e18"
      define_method(:install) do
        bin.install "webu"
      end
    end
  end

  def caveats
    <<~EOS
      webu runs its own Chromium (a pinned revision), fetched once on the
      first launch — about 175–250 MB into the cache directory (macOS:
      ~/Library/Caches/webu, Linux: ~/.cache/webu). After an upgrade that
      pins a new revision, `webu browser update` fetches it.

      Settings and bookmarks live in ~/.config/webu; history, session,
      downloads and the browser profile in ~/.webu/datas.

      A Nerd Font terminal profile is required: links, media, panels and
      the header are drawn with Nerd Font glyphs.
    EOS
  end

  test do
    system "#{bin}/webu", "version"
  end
end
