# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webu < Formula
  desc "terminal browser (u-family) — headless Chromium's accessibility tree, drawn as a TUI: tabs, bookmarks, history, downloads, DevTools"
  homepage "https://github.com/vulcanshen/webu"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vulcanshen/webu/releases/download/v0.3.0/webu_0.3.0_darwin_amd64.tar.gz"
      sha256 "3465d122f206412ee3d91182bce6a425a032e49a0faae177c4c7b54e09fd442b"

      define_method(:install) do
        bin.install "webu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vulcanshen/webu/releases/download/v0.3.0/webu_0.3.0_darwin_arm64.tar.gz"
      sha256 "d2181f2e82b383c582c137b22f254203530f2e35eb301fe365b72be78079de36"

      define_method(:install) do
        bin.install "webu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vulcanshen/webu/releases/download/v0.3.0/webu_0.3.0_linux_amd64.tar.gz"
      sha256 "c50695ea8c2b636e244d400b7487ea83f92c8227defb209896dc237ef49a42c8"
      define_method(:install) do
        bin.install "webu"
      end
    end
  end

  def caveats
    <<~EOS
      webu runs its own Chromium (a pinned revision), fetched once on the
      first launch — about 175–250 MB into the cache directory (macOS:
      ~/Library/Caches/webu, Linux: ~/.cache/webu). After an upgrade that
      pins a new revision, `webu browser update` fetches it.

      Settings and bookmarks live in ~/.config/webu; history, session,
      downloads and the browser profile in ~/.webu/datas.

      A Nerd Font terminal profile is required: links, media, panels and
      the header are drawn with Nerd Font glyphs.
    EOS
  end

  test do
    system "#{bin}/webu", "version"
  end
end
