# This file was generated by GoReleaser. DO NOT EDIT.
cask "filu" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "88092ef4867f6a8206e86ffc7204ad6c4fe61900747bb49b40819b3fb0294eed"
      url "https://github.com/vulcanshen/filu/releases/download/v#{version}/filu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a01ff0d4234a7f8e101e92a2f29d7272a08f9451ff1e88838b74a7f25ae76179"
      url "https://github.com/vulcanshen/filu/releases/download/v#{version}/filu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f2314f65b435b784bf43b6590ea302f311fc87bb9b804a5d4b0e51ec7f0c89ec"
      url "https://github.com/vulcanshen/filu/releases/download/v#{version}/filu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2dbcad7c895777d8439e807618813bdfb2e7e59572c5e4796d7822e04ed2f94"
      url "https://github.com/vulcanshen/filu/releases/download/v#{version}/filu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "filu"
  desc "ZLC terminal file manager (kbu u-family) — content search, split preview, carry-bucket"
  homepage "https://github.com/vulcanshen/filu"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fd",
      "ripgrep",
    ]

  binary "filu"

  # No zap stanza required

end
